@echo "%~dp0utils"
set $Dos_Ori=\\cg11.local\partage\Finances\SPBPF\DETTE - TRESORERIE\GESTION DE DETTE  PROPRE\MANDATEMENT DETTE\EXTRACTION DES FICHIERS MENSUELS\INTERFACE CGI\
@echo %$Dos_Ori%

"\\cg11.local\partage\Finances\SPBPF\DETTE - TRESORERIE\GESTION DE DETTE  PROPRE\MANDATEMENT DETTE\EXTRACTION DES FICHIERS MENSUELS\INTERFACE CGI\NE_PAS_SUPPRIMER\Transfert_GDA.bat" GDAR mandatement.txt

